server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_abuse_detection?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
    username: root
    password: chien2005

app:
  bootstrap-admin:
    enabled: true
    username: admin
    password: admin
    email: admin@example.com

jwt:
  signerKey: ${JWT_SIGNER_KEY:374ccce55ce533f7dcc8bc02b136d0b5963d0ed654f532313e1e49862fe68c11}
